---
title: "#yurult v0.1.0を開催した"
created_at: 2020-06-02 16:09:29 +0900
draft: true
kind: "article"
tags:
  - "yurult"
  - "event"
locale: "ja_JP"
description: "「ゆるいオンラインLT会 v0.1.0」(#yurult)を開催したので概要と反省を書きます"
twitter: ""
---

2週間前に「ゆるいオンラインLT会」というオンラインイベントを開催させていただきました。
流石に2週間経ったのでもう話題性は薄れてきてしまったとは思うのですが、clusterで開催されるVR機材を持たない人を対象としたイベントはそこまで多くないのではないかと思います。
ですから、資料として残すべきと思い、この記事の筆を取りました。

=== 事前準備

必要な情報やTODOリストなど共有すべきことはTwitterではなく、link:https://hackmd.org/[HackMD]のOSS版、link:https://codimd.org/[CodiMD]のlink:https://demo.codimd.org[demo版]を利用させていただきました。
私は文書の共有を行う際はHackMD/CodiMDを結構重宝しています。
長い文書を共有したい、かつ相手がMarkdownを読み書きできるのであればGoogle
Docsより軽量だし楽かなと思ってます。

==== 配信テスト

YouTubeとclusterの接続デモ、clusterでの配信によるマシンの負荷実験を目的として1週間前程に行ないました。

==== connpassページを書いた

cluster経験者が少ないことを想定して、clusterの入門資料やヘルプをconnpassページ内にリンクとして掲載することで敷居を下げようとしました。

==== Google Formでアンケートを書いた

終了後に参加者に送付するアンケートを書きました。

=== 登壇内容

当日は6人の方に登壇していだだきました。登壇順でざっくりと感想を述べようと思います。 +
なお、YouTubeのアーカイブもあります。

video::c2lEu9WWfBg[youtube]

==== ぎもちんさん「C#のキモイ高速プログラミング」

C# を触ったことすらないのでポインタがさわれること自体初耳でした。
1ns以下で可読性と引き換えに配列の型が変換できるのは凄いなあと思いました。
ふと思ったのですが、RustもCrystalもF#もそうなんですけど、ブラットでいろいろできる裏ワザっぽいやつって色々な言語であるなあと。

==== かるさん「Denoに5分で入門してみた」

NPMのnode_modulesディレクトリがあまり好きではないという個人的な理由もありますが、
Deno v1.0.0がリリースされたのはYarn v2のrc版リリースと共に、ここ最近Webエンジニア界隈を賑わせたニュースといっていいのではないかなと個人的には思っています。
DenoとはNodeの作者がNodeでの反省をもとにRustで実装したJS/TS処理系で、セキュリティに気を使っている、JSの標準規格に準拠している、ネイティブでTSがコンパイルできるということが特徴です。
GolangやRustに影響された点を随所に見ることができます。

==== uemura5683さん「Microcms + nuxt.jsで個人ブログサイトをデプロイした件」

ヘッドレスCMSがNuxtやNextと組み合わせてブログなどに使われつつあるというトレンドを知ってはいましたが、そこまで深くは知りませんでした。
Microcmsって問い合わせフォームのようなClientからServerにデータを送信する処理が作れたことは初耳でした。
事前にビルドするスタイルのHugoやJekyllではできないこともできるのはヘッドレスCMSの強みだなと感じました。

また、私もNuxt.jsのプロダクトをレンタルサーバで手動デプロイしたことはあるのですが、これがなかなかつらいです。
NetlifyはNuxtのビルドからデプロイまで自動でやってくれるのでありがたい存在だなあと再認識しました。

==== Uniokaさん「DiscordでクソBotを作った」

スライド全体にユーモアがちりばめられおもしろかったです。
コマンドを打つとボイスチャンネルにBotが入ってきてEDMが流して帰るというBotだったのですが、発想がおもしろかったです。
Typoの達人などユーモアに溢れるBotが他にも限界開発鯖にはあるらしくおもしろいなあと。

==== fly_in_pigさん 「今日はいい天気ですね。ところで、セミコロンは消えるべきなのです。」

C/C++ においてセミコロンは逃げられないものかと思っていました。
しかしC/C++ の黒魔術？によってどうも逃げられることを知って、C/C++ の世界(というか黒魔術？)は広いなあと感じました。
ところでなんでRustはセミコロン採用してるんだろうか……。

==== Takumiさん「転職に伴うスキルチェンジへの取り組み」

私は学生なのですが、この学校に入学してかたそれなりに在籍年数がある年になりました。
そうなると身近に就職する先輩がいたりするわけですが、就職する先輩はいても転職する人は身近に居ません。
ですので、どのように転職するのか、どう方針を立てていくべきなのかということが参考になりました。
AWS、Azureはやっぱりトレンドなのか……。クラウドは料金体系がVPSより高いのでつらいですが、勉強しようと思いました。 +
また、私もそろそろ社会人になるのか……という複雑な思いも。

=== 反省

==== スライドとスライドの間でトークを入れたかった

反省会でも言ったのですが、スライドとスライドの間でトークを入れたかったです。
これは私がよく参加させていただいている、高専カンファレンスにてやられているのを見ておもしろそうだなと思ったものです。
ただ、様々な人が様々な分野の発表するというこのLT会の特性上、コメントがむずかしいし、トーク力が要るなあと思ったのでした……。

==== 最初緊張しまくって司会がテンパったり、噛みまくったり

私の上がり症をがんばって直します。それしかないかなーと。

==== LT前の接続テスト

学内でのLT会ではやっていたけど完全に忘れていました。
後述ですが、これが一番の問題点だと思っています。気付かなかった私を殴りたい……。

==== clusterならではの話

. 音声関連の不具合
+
音声関連の不具合は多かったです。
これは前述した通り、LT前の接続テストを行っていなかったという問題も一部かかわっているとは思いますが、
具体的な症状としては音声が急に入らなくなる、ダブる、プツプツ途切れるという事が多発しました。
プツプツ途切れるという症状はcluster側でもYouTube側でも発生し、YouTubeの方が回数は多かったです。
.. やはり、一番の問題点は接続テストをしなかったことに起因しているのかなと思います。
. clusterの機能について
.. Twitterとの連携コメント
+
clusterにはTwitterとの連携コメントという機能があります。
これはclusterとTwitterのアカウントを連携するとclusterのイベントでした自分のコメントがTwitterにも投稿されるものです。
主催者としては参加者を増やすことにも繋がることなので重要かなと思っています。
.. 写真撮影
.. エモーション
+
参加してくださった方が自発的にやっていただいきました。感謝です。
会場では原則ミュートというルールへの協力の下運営をしていたので、登壇者にとっては静かな会場と対峙しないといけないわけです。
これは緊張する一因にもなりえるのではないかと個人的には思いました。
本会は題名にある通り、「ゆるい」をモットーにやっています。
ですから、登壇しづらさはできるだけ排除するべきです。
connpassにはclusterの入門資料をリンクとして掲載してはいますが、これらの機能でもっと盛り上げることも可能かと考えられます。
よって、最初にこれらの機能を簡潔にでも説明すべきだったかなと思っています
. YouTubeのコメントが入ってこない
+
これはリハーサルでも起きました。
ahttps://www.youtube.com/watch?v=tYs9bwY-2Gg[WebxR Tech Tokyo #0]のyoutubeアーカイブではこのようなことは起こっていないため、clusterに問い合わせてみないとわからないです。
ただ、Youtube側のコメントをキャッチしづらいのでこの問題はかなり重要かもしれません。
. connpassページの資料の数
+
connpassにはたくさんclusterの資料をまとめておいたのはよかったという声をいただいたものの、それでも、「戸惑いながらやった」という方も多かった。

==== cluster側の開場時間

cluster側でも遅くとも5分前の開場をするべきだったと思っています。
youtube側はそのようにしていましたが、cluster側はそのように設定するのを忘れていました。 +
また、LT前の接続テストも考慮するならば30〜15分前などでもいいと思いました。

==== 反省会

. 反省会での話題の振り方がざっくりすぎた
+
当日に10分程度で作ったざっくりと抽象的な話題はすぐに終わってしまいました。
参加者のみなさんが話を繋げてくださったことに感謝しかありません。 +
次にチャンスがあり、その際に反省会もやるならば、話題をその場で作り、それをベースに話を進めるというスタイルだとよさそうかなと考えています。
例としてはlink:https://cokonpile.connpass.com/[Co-KoNPILe]のように懇親会はもくもく会をやられています。

=== 最後に

みんなでわいわいできたらいいなあとふわっとした動機で計画していたこのLT会ですが、楽しんでいただけたら幸いです。 +
また、clusterで何かLT会を主催されるという方の役に経ったら幸いです。
