baseURL = "https://eniehack.netlify.com"
languageCode = "ja"
defaultcontentlangage = "en"
theme = "hermit"
title = "eniehack blog"
hasCJKLanguage = true
enableEmoji = true 

[author]
	name = "Nakaya"
	avatarurl = "images/avatar.png"

[taxonomies]
    tag = "tags"
	
[params]
	dateform = "January 02, 2006"
	dateformShort = "January 02, 2006"
	dateformNum = "2006/01/02"
	dateformNumTime = "2006/01/02 15:04 -0700"
	
[[params.social]]
	name = "github"
	weight = 1
	url = "https://github.com/eniehack/"
	
[[params.social]]
	name = "mastodon"
	weight = 2
	url = "https://mstdn.maud.io/@eniehack/"

[[params.social]]
	name = "twitter"
	weight = 3
	url = "https://twitter.com/eniehack/"
	
[[menu.main]]
	name = "Blog"
	weight = 1
	url = "https://eniehack.hatenablog.com/"
	
[[menu.main]]
	name = "About"
	weight = 2
	url = "/about/"
	
[[menu.main]]
	name = "Works"
	weight = 3
	url = "/works/"
	
