baseURL = "https://eniehack.netlify.com"
languageCode = "ja"
defaultcontentlangage = "en"
theme = "coder"
title = "caffeine"

[params]
	author = "caffeine"
	info = "Beginner of Web programmer."
	description = "caffeine's portfolio page"
	
	avatarurl = "images/avatar.png"
	
	dateformat = "September 15, 2018"

    hideCredits = false
hideCopyright = false
	
[[params.social]]
	name = "GitHub"
	weight = 1
	icon = "fab fa-github fa-3x"
	url = "https://github.com/eniehack/"
	
[[params.social]]
	name = "Mastodon"
	weight = 2
	icon = "fab fa-mastodon fa-3x"
	url = "https://mstdn.maud.io/@eniehack/"

[[params.social]]
	name = "Twitter"
	weight = 3
	icon = "fab fa-twitter fa-3x"
	url = "https://twitter.com/eniehack/"
	
[[menu.main]]
	name = "Blog"
	weight = 1
	url = "https://eniehack.hatenablog.com/"
	
[[menu.main]]
	name = "About"
	weight = 2
	url = "/about/"
	
[[menu.main]]
	name = "Works"
	weight = 3
	url = "/works/"
	