baseURL = "https://eniehack.netlify.com"
languageCode = "ja"
defaultcontentlangage = "ja"
theme = "my-theme"
title = "caffeine"

[params]
	author = "Nakaya(caffeine)"
	info = "高専生"
	introduction = "(webエンジニア|クリエイター)志望高専生。読書も好きです。理系学生だけど(社会科学|人文科学)にも興味あり。Python(Django/Flask)/LuaLaTeX"
	avatarurl = "images/avatar.png"
	
	[[params.social]]
		name = "GitHub"
		weight = 1
		icon = "fab fa-github fa-3x"
		url = "https://github.com/eniehack"
		
	[[params.social]]
		name = "Mastodon"
		weight = 2
		icon = "fab fa-mastodon fa-3x"
		url = "https://mstdn.maud.io/@eniehack"

	[[params.social]]
		name = "Twitter"
		weight = 3
		icon = "fab fa-twitter fa-3x"
		url = "https://twitter.com/eniehack"

	[[params.jsonld]]
		name = "caffeine"
		url = "https://twitter.com/eniehack"
		image = "https://eniehack.netlify.com/image/avatar.png"
