baseURL = "https://eniehack.netlify.com"
languageCode = "ja"
defaultcontentlangage = "ja"
theme = "hermit"
title = "Nakaya's blog"
hasCJKLanguage = true
enableEmoji = true 
enableGitInfo = true
description = "Nakaya's blog"

[author]
	name = "Nakaya"

[taxonomies]
    tag = "tags"
	
[params]
	dateform = "January 02, 2006"
	dateformShort = "January 02, 2006"
	dateformNum = "2006/01/02"
	dateformNumTime = "2006/01/02 15:04 -0700"
    locale = "ja_JP"
	ogp_image = "avatar.png"
    twitter = "eniehack"
	
[[params.social]]
    name = "github"
	class = "fa fa-github"
    url = "https://github.com/eniehack/"

[[params.social]]
    name = "Keybase"
	class = "fa fa-keybase"
	url = "https://keybase.io/eniehack/"

[[params.social]]
    name = "Misskey"
	class = "fa fa-activitypub"
	url = "https://misskey.io/@eniehack/"

[[params.social]]
    name = "mastodon"
	class = "fa fa-mastodon"
	url = "https://mstdn.maud.io/@eniehack/"

[[params.social]]
    name = "twitter"
	class = "fa fa-twitter"
	url = "https://twitter.com/eniehack/"
	
[[menu.main]]
	name = "Blog"
    url = "/blog/"
	
[[menu.main]]
	name = "About"
	url = "/about/"
	
[[menu.main]]
	name = "Works"
	url = "/works/"
