baseURL = "https://eniehack.netlify.com"
languageCode = "ja"
defaultcontentlangage = "ja"
theme = "hermit"
title = "eniehack blog"
hasCJKLanguage = true
enableEmoji = true 

[author]
	name = "Nakaya"
	avatarurl = "images/avatar.png"

[taxonomies]
    tag = "tags"
	
[params]
	dateform = "January 02, 2006"
	dateformShort = "January 02, 2006"
	dateformNum = "2006/01/02"
	dateformNumTime = "2006/01/02 15:04 -0700"
	
[[params.social]]
    name = "github"
	class = "fa fa-github"
    url = "https://github.com/eniehack/"

[[params.social]]
    name = "Keybase"
	class = "fa fa-keybase"
	url = "https://keybase.io/eniehack/"

[[params.social]]
    name = "Misskey"
	class = "fa fa-activitypub"
	url = "https://misskey.io/@eniehack/"

[[params.social]]
    name = "mastodon"
	class = "fa fa-mastodon"
	url = "https://mstdn.maud.io/@eniehack/"

[[params.social]]
    name = "twitter"
	class = "fa fa-twitter"
	url = "https://twitter.com/eniehack/"
	
[[menu.main]]
	name = "Blog"
	weight = 1
	#url = "https://eniehack.hatenablog.com/"
  url = "/blog/"
	
[[menu.main]]
	name = "About"
	weight = 2
	url = "/about/"
	
[[menu.main]]
	name = "Works"
	weight = 3
	url = "/works/"